# Generated by Django 5.0.6 on 2024-06-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthplace', models.TextField()),
                ('residence', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=3)),
                ('university', models.TextField()),
                ('major', models.CharField(max_length=100)),
                ('hobbies', models.TextField()),
            ],
        ),
    ]
