# Generated by Django 5.0.6 on 2024-06-06 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='major',
            new_name='specialty',
        ),
    ]
